/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hh_androidjni_PtlmanerJni */

#ifndef _Included_com_hh_androidjni_PtlmanerJni
#define _Included_com_hh_androidjni_PtlmanerJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hh_androidjni_PtlmanerJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hh_androidjni_PtlmanerJni_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
